### ISSUE TITLE
[Marketplace 10x / API] Incorrect returned orders

### ISSUE THREAD

**Issue by pisuthd** [tamago-finance/marketplace-scb10x#156]
Some collection returned incorrect orders like following:
https://marketplace-10x.tamago.finance/orders/collection/0x2953399124f0cbb46d2cbacd8a89cf0599974963

**Comment by Moopz-Dev** [comment]
This is caused due to the target NFT collection address could be Opensea's Shared Store front address. This means that all nfts minted from this contract address (which also exist in our collections database) will be returned.

This issue could be complicated and will be considered in a future opportunity.

**Comment by Moopz-Dev** [comment]
Manually editted the collection's name and description to that of Opensea Storefront.
